In [1]:
#1D array
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#0D array
import numpy as np
arr= np.array(11)
print(arr)

11


In [4]:
#2D array
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3D array with two 2D arrays
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
#check dimensions of array

import numpy as np

# 0-D array (scalar)
a = np.array(42)

# 1-D array
b = np.array([1, 2, 3, 4, 5])

# 2-D array
c = np.array([[1, 2, 3], [4, 5, 6]])

# 3-D array
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

# Print number of dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
#get 2nd and 3rd index of element and add them
import numpy as np
arr= np.array([1,2,3,4])
print(arr[2])

3


In [6]:
#from 2 arrays get index
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [4]:
#to check index for 1d array
import numpy as np
arr= np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [10]:
#SLICING index1 to index5
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [14]:
#start index not mentioned
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


In [15]:
#start and end index not mentioned
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [17]:
#from index4 to end
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [19]:
#negative slicing
#from index 3 from the end to index 1 from end
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [20]:
#STEP
import numpy as np
arr=([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2, 4]


In [1]:
#return every other element from the entire array
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [2]:
#slicing 2D array
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [6]:
#examples
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,2])

6


In [7]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2:])

[[1 2 3]
 [4 5 6]]


In [10]:
#
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice = arr[:, 1:3]
print(col_slice)


[[2 3]
 [5 6]
 [8 9]]
