In [3]:
#Convert a Python list into a NumPy array
import numpy as np

my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)

print(arr)

[1 2 3 4 5]


In [5]:
#Reverse a 1D NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reverse_arr = arr[::-1]

print(reverse_arr)

[5 4 3 2 1]


In [7]:
 #Create a 3×3 identity matrix
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Create a 4×4 array and extract its first row and last column
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

first_row = arr[0, :]
last_column = arr[:, -1]

print("First Row:")
print(first_row)

print("Last Column:")
print(last_column)

First Row:
[1 2 3 4]
Last Column:
[ 4  8 12 16]


In [10]:
 #Create a 4×4 NumPy array and extract the first two rows and first two columns
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

result = arr[:2, :2]

print(result)

[[1 2]
 [5 6]]
